# Generated by Django 4.2.6 on 2023-10-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=100)),
                ('bemail', models.EmailField(max_length=254)),
                ('bownerinfo', models.CharField(max_length=100)),
                ('baddressl1', models.CharField(max_length=100)),
                ('baddressl2', models.CharField(max_length=100)),
                ('bsize', models.IntegerField()),
            ],
            options={
                'db_table': 'business',
            },
        ),
    ]
